apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-system
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chinmaya10000/kubernetes-manifest.git
    targetRevision: main
    path: overlays/dev
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
